plugins {
    id 'java'
}

group = 'com.erikk.walljump'
version = '4.0.3'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = 'worldguard'
        url = 'https://maven.enginehub.org/repo/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    compileOnly 'com.sk89q.worldguard:worldguard-bukkit:7.0.17'
    implementation fileTree(dir: 'libs', include: '*.jar')
    compileOnly 'org.jetbrains:annotations:24.0.1'
}
